params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100

networks:
  test_run:
    path_to_network_params: projects/scene_generation/inverse_graphics/dense_descriptors/trained_models/test_run/prime_box/000501.pth
  test_run_2500:
    path_to_network_params: projects/scene_generation/inverse_graphics/dense_descriptors/trained_models/test_run_2500/prime_box/002501.pth

output_dir: analysis
