params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100

networks:
  test_run_updated_torch:
    path_to_network_params: projects/scene_generation/inverse_graphics/supervised_dense_descriptors/trained_models/test_run_updated_torch/prime_box/002001.pth
output_dir: analysis
